trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build_Stage
    displayName: Build Stage
    jobs: 
    - job: BuildNuget
      displayName: Build Nuget packages
      variables:
        BuildConfiguration: release
      steps:
      
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: '**/*.csproj'
          feedsToUse: 'select'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '**/*.csproj'
          arguments: '--configuration $(BuildConfiguration)'
      
      - task: DotNetCoreCLI@2
        inputs:
          command: 'pack'
          packagesToPack: '**/*.csproj'
          versioningScheme: 'off'
      
      - task: DotNetCoreCLI@2
        inputs:
          command: 'push'
          packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
          nuGetFeedType: 'internal'
          publishVstsFeed: '9d6b70b9-4b35-46b8-bb0d-8c764684a07d/2de3d97a-833b-4348-ae62-8c5742daa7ba'